title: neko
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
github:
  tar_url: https://github.com/ExtremeFLOW/neko/releases/download/v0.9.1/neko-0.9.1.tar.gz


