title: neko
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
github:
  tar_url: https://github.com/ExtremeFLOW/neko/releases/download/v1.0.0/neko-1.0.0.tar.gz


