name: Check Code Style

# Controls when the action will run.
on:
  workflow_call:
    inputs:
      json-fortran-version:
        description: "The version of the JSON-Fortran library to use."
        type: string
        required: false
        default: "8.4.0"

jobs:
  linting:
    name: Linting
    uses: ./.github/workflows/check_lint.yml

  formatting:
    name: Formatting
    uses: ./.github/workflows/check_format.yml

  depend:
    name: Check .depend file
    uses: ./.github/workflows/check_depend.yml
    with:
      json-fortran-version: ${{ needs.prepare.outputs.json-fortran-version }}
